### ISSUE TITLE
CentOS issue permission denied

### ISSUE THREAD

**Issue by mennodekker** [obiba/rock#6]
We did a rpm install on CentOS 8 and had problems with permissions:
cannot open file '/var/lib/rock/conf/system.info.R': Permission denied

I solved it by recursively adding execute rights to the directory /etc/rock for the owner.
`sudo chmod -R -o+X /etc/rock`

Not sure if that is correct or if I need to change in other places. It now shows system info in opal.
Reporting here so it can be solved in the rpm.

**Comment by ymarcon** [comment]
Please have a try with rock 1.0.8.

**Comment by mennodekker** [comment]
Thanks for the quick fix, I can confirm the problem is solved now

**Comment by ymarcon** [comment]
Thanks for the report! we use ubuntu, then centos packaging issues can be difficult to spot.
