### ISSUE TITLE
Creation of /usr/share/rock link fails on upgrade

### ISSUE THREAD

**Issue by bjornwiberguuse** [obiba/rock#7]
On RPM upgrades (or downgrades) of rock (e.g. from rock-1.0.8-1 to rock-1.0.9-1), the creation of the /usr/share/rock symlink in the postinstall scriptlet of the RPM fails:

```
ln: target ‘/usr/share/rock’ is not a directory
```

This appears to be because multiple /usr/share/rock-* directories appear to exist simultaneously, before the upgrade (or downgrade) has been completed. This in turn causes Rock startup to fail.

I would suggest adding the actual symlink as a "file" in the RPM instead of handling it in the scriptlets, if possible.

**Comment by ymarcon** [comment]
Thanks for the report, please have a try with release 1.0.10.
